name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: nooblk-98
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
            assets/ocean.gif?generator_ocean

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update snake animation [skip ci]"
          file_pattern: assets/*.svg assets/*.gif
